using SharpEmu.HLE;
using System.Buffers.Binary;
namespace SharpEmu.Libs.Psml;
public static class PsmlExports {
 const int NI=unchecked((int)0x8a810001),IP=unchecked((int)0x8a810009),IV=unchecked((int)0x8a81000d); static bool init;
 static int R(CpuContext c,int v)=>c.SetReturn(v); static bool W(CpuContext c,ulong p,ulong n){Span<byte>b=stackalloc byte[24];BinaryPrimitives.WriteUInt64LittleEndian(b,0x200000);BinaryPrimitives.WriteUInt64LittleEndian(b[8..],0x200000);BinaryPrimitives.WriteUInt64LittleEndian(b[16..],n);return c.Memory.TryWrite(p,b);}
 [SysAbiExport(Nid="3WVD91e12ZQ",ExportName="scePsmlInitialize",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Init(CpuContext c){init=true;return R(c,0);}
 [SysAbiExport(Nid="+2KpvixvL6E",ExportName="scePsmlGetMainMemoryRequirements",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Main(CpuContext c){if(!init)return R(c,NI);var o=c[CpuRegister.Rdi];var p=c[CpuRegister.Rsi];if(o==0||p==0)return R(c,IP);Span<byte>b=stackalloc byte[4];if(!c.Memory.TryRead(p,b))return R(c,(int)OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);var t=BinaryPrimitives.ReadUInt32LittleEndian(b);var n=t switch{0=>52UL,1=>197UL,2=>149UL,_=>0UL};return n==0?R(c,IV):(W(c,o,n)?R(c,0):R(c,(int)OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT));}
 [SysAbiExport(Nid="EO9YQXmJEN8",ExportName="scePsmlGetContextMemoryRequirements",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Ctx(CpuContext c)=>!init?R(c,NI):(c[CpuRegister.Rdi]==0?R(c,IP):(W(c,c[CpuRegister.Rdi],1)?R(c,0):R(c,(int)OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT)));
 [SysAbiExport(Nid="IMlj247LdTo",ExportName="scePsmlGetContextMemoryRequirements",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Ctx2(CpuContext c)=>Ctx(c);
 [SysAbiExport(Nid="sjTyYheKTrU",ExportName="scePsmlGetContextMemoryRequirements",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Ctx3(CpuContext c)=>Ctx(c);
 [SysAbiExport(Nid="ArakEpzsZo0",ExportName="scePsmlGetContextMemoryRequirements",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Ctx4(CpuContext c)=>Ctx(c);
 [SysAbiExport(Nid="VGjrQa-WqdU",ExportName="scePsmlGetContextMemoryRequirements",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Ctx5(CpuContext c)=>Ctx(c);
 static bool Obj(CpuContext c,ulong p){Span<byte>b=stackalloc byte[4];return p!=0&&c.Memory.TryRead(p,b)&&(BinaryPrimitives.ReadUInt32LittleEndian(b)==0xa9c4||BinaryPrimitives.ReadUInt32LittleEndian(b)==0x9231);}
 [SysAbiExport(Nid="AHalTX9wFZY",ExportName="scePsmlGetWorkAreaSize",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Work(CpuContext c){if(!init)return R(c,NI);if(!Obj(c,c[CpuRegister.Rdi]))return R(c,unchecked((int)0x8a810005));var p=c[CpuRegister.Rsi];if(p==0)return R(c,IP);Span<byte>b=stackalloc byte[4];BinaryPrimitives.WriteUInt32LittleEndian(b,0x600);return c.Memory.TryWrite(p,b)?R(c,0):R(c,(int)OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);}
 [SysAbiExport(Nid="RUNLFro+qok",ExportName="scePsmlDispatch",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Dispatch(CpuContext c)=>!init?R(c,NI):(!Obj(c,c[CpuRegister.Rdi])?R(c,unchecked((int)0x8a810005)):(c[CpuRegister.Rsi]==0||c[CpuRegister.Rdx]==0?R(c,IP):R(c,0)));
 [SysAbiExport(Nid="GJY0MvuTcs8",ExportName="scePsmlRequestCapture",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Capture(CpuContext c)=>!init?R(c,NI):(Obj(c,c[CpuRegister.Rdi])?R(c,0):R(c,unchecked((int)0x8a810005)));
 [SysAbiExport(Nid="LXq+6mIxpCw",ExportName="scePsmlValidateObject",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Validate(CpuContext c)=>Capture(c);
 [SysAbiExport(Nid="FSGaTQze0UY",ExportName="scePsmlValidateObject",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Validate2(CpuContext c)=>Capture(c);
 [SysAbiExport(Nid="eWoKNeB6V-k",ExportName="scePsmlSharedResourcesInitialize",Target=Generation.Gen5,LibraryName="libScePsml")] public static int SharedInit(CpuContext c){if(!init)return R(c,NI);var o=c[CpuRegister.Rdi];var p=c[CpuRegister.Rsi];if(o==0||p==0)return R(c,IP);Span<byte>b=stackalloc byte[4];BinaryPrimitives.WriteUInt32LittleEndian(b,0xa9c4);return c.Memory.TryWrite(o,b)?R(c,0):R(c,(int)OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);}
 [SysAbiExport(Nid="jEevBXmagOQ",ExportName="scePsmlSharedResourcesFinalize",Target=Generation.Gen5,LibraryName="libScePsml")] public static int SharedFin(CpuContext c)=>!init?R(c,NI):(c[CpuRegister.Rdi]==0?R(c,unchecked((int)0x8a810014)):R(c,0));
 static int ContextInit(CpuContext c){if(!init)return R(c,NI);var o=c[CpuRegister.Rdi];var p=c[CpuRegister.Rsi];if(o==0||p==0)return R(c,IP);Span<byte>b=stackalloc byte[4];BinaryPrimitives.WriteUInt32LittleEndian(b,0x9231);return c.Memory.TryWrite(o,b)?R(c,0):R(c,(int)OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);}
 [SysAbiExport(Nid="2ecEbQaf9VU",ExportName="scePsmlContextInitialize",Target=Generation.Gen5,LibraryName="libScePsml")] public static int CInit(CpuContext c)=>ContextInit(c);
 [SysAbiExport(Nid="vUk2pWMx3KQ",ExportName="scePsmlContextInitialize",Target=Generation.Gen5,LibraryName="libScePsml")] public static int CInit2(CpuContext c)=>ContextInit(c);
 [SysAbiExport(Nid="gxv3i+MTEzU",ExportName="scePsmlContextInitialize",Target=Generation.Gen5,LibraryName="libScePsml")] public static int CInit3(CpuContext c)=>ContextInit(c);
 [SysAbiExport(Nid="JaLBe0P3jSU",ExportName="scePsmlContextFinalize",Target=Generation.Gen5,LibraryName="libScePsml")] public static int CFin(CpuContext c){if(!init)return R(c,NI);var p=c[CpuRegister.Rdi];if(!Obj(c,p))return R(c,unchecked((int)0x8a810005));Span<byte>b=stackalloc byte[4];b.Clear();return c.Memory.TryWrite(p,b)?R(c,0):R(c,(int)OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);}
 [SysAbiExport(Nid="GHna9-DvnUk",ExportName="scePsmlGetProgress",Target=Generation.Gen5,LibraryName="libScePsml")] public static int Progress(CpuContext c){if(!init)return R(c,NI);if(!Obj(c,c[CpuRegister.Rdi]))return R(c,unchecked((int)0x8a810005));var p=c[CpuRegister.Rsi];if(p==0)return R(c,IP);Span<byte>b=stackalloc byte[4];b.Clear();return c.Memory.TryWrite(p,b)?R(c,0):R(c,(int)OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);}
}

